[package]
name = "rust_os"
version = "0.1.0"
authors = ["Ziyi Yan <ziyi.yan@foxmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bootloader = "0.9.8"